Update README
PortZeroGroup/PZ-DiscordBot pull request #9
Opened 2021-03-07 19:50 UTC by qntnt

2021-03-07 20:18 UTC, The-Tasty-Jaffa requested changes
These steps don't entirely follow how Red bot is deployed.
This is particularly true for step 5

Linking [this](https://docs.discord.red/en/stable/getting_started.html) Could be a good idea too.
This is certainly a great start!

2021-03-07 21:19 UTC, The-Tasty-Jaffa commented
This looks good.
We could direct people towards https://docs.discord.red/en/stable/install_linux_mac.html
and https://docs.discord.red/en/stable/install_windows.html respectively too.
Since it has all the updated stuff, reasonably comprehensive and simple to follow.

2021-03-09 02:14 UTC, The-Tasty-Jaffa commented on README.md
> +We will automatically deploy release branches ([TODO](https://github.com/PortZeroGroup/PZ-DiscordBot/issues/8)) when commits are made. To do this safely, changes will merge into a "staging" branch ([
Not Sure about this bit.
None of this is yet implemented, it might be worth removing this section for now.

2021-03-09 03:14 UTC, The-Tasty-Jaffa approved these changes

2021-03-09 12:50 UTC, daswanderer commented on README.md
> +1. Join the Port Zero discord server and join the project (#discord-bot-dev channel)
Nit: Can we make this a link to the PZ discord

2021-03-09 12:50 UTC, daswanderer approved these changes

2021-03-09 13:26 UTC, MrLotU commented on README.md
> +1. Join the Port Zero discord server and join the project (#discord-bot-dev channel)
```suggestion
1. Join the [Port Zero discord server](https://discord.gg/jmHWZA4vg5) and join the project (#discord-bot-dev channel)
```

2021-03-09 21:11 UTC, merged